sonar.organization=nz-adddress-checker
sonar.projectKey=NZ-Adddress-Checker_Address-Checker-App
sonar.host.url=https://sonarcloud.io
sonar.projectName=Address Checker App

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/dist/**,**/build/**

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
